const express = require('express');
const router = express.Router();
const AuthController = require('../controllers/AuthController');
router.post('/login', AuthController.login);
router.post('/register', AuthController.register);
router.post('/forgot-password', AuthController.forgotPassword);
router.post('/reset-password', AuthController.resetPassword);
router.post('/google', AuthController.googleAuth);
router.post('/microsoft', AuthController.microsoftAuth);
router.post('/apple', AuthController.appleAuth);
router.post('/logout', AuthController.logout);
module.exports = router;
